# Generated by Django 4.2.3 on 2023-07-19 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.ImageField(upload_to='images/')),
                ('about_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_image', models.ImageField(upload_to='images/Competency/')),
                ('competency_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_text', models.CharField(max_length=20)),
                ('second_text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_summary', models.CharField(max_length=100)),
                ('portfolio_image', models.ImageField(upload_to='images/Portfolio/')),
                ('portfolio_source', models.URLField()),
                ('portfolio_about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_tech', models.CharField(max_length=50)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_tech', to='home.portfolio')),
            ],
        ),
    ]
