# Generated by Django 4.2.3 on 2023-07-19 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.ImageField(default='logo.png', upload_to='images/Services/Icon/')),
                ('service_text', models.CharField(default='None', max_length=20)),
                ('service_image', models.ImageField(default='logo.png', upload_to='images/Services/')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_text', to='home.services')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('john', models.ImageField(upload_to='images/Services/')),
                ('service_im', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_image', to='home.services')),
            ],
        ),
    ]
