# Generated by Django 4.2.3 on 2023-07-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_services_servicestext_servicesimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
                ('Linkedin', models.URLField()),
                ('Instagram', models.URLField()),
                ('tiktok', models.URLField()),
                ('github', models.URLField()),
                ('upwork', models.URLField()),
                ('fiverr', models.URLField()),
            ],
        ),
    ]
