# Generated by Django 4.2.3 on 2023-08-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_john_servicesimage_img_s_portfolioimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='competency',
            name='competency_image',
            field=models.ImageField(upload_to='media/images/Competency/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.ImageField(upload_to='media/images/Portfolio/'),
        ),
        migrations.AlterField(
            model_name='portfolioimages',
            name='portfolio_img',
            field=models.ImageField(upload_to='media/images/Portfolio/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_image',
            field=models.ImageField(default='logo.png', upload_to='media/images/Services/'),
        ),
    ]
